
server:
  port: 8080
---

spring:
  profiles: default
#   JPA 설정
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
    show_sql: true
    format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

#   MySQL DB설정
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/home?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
#    username: test
#    password: test
    username: ENC(Idv0U0KIbsslp/99l3hBN887zHbbzuPCPdrDurPkt2M=)
    password: ENC(ivMd8IXHu+N4K9zVNB3+9F2tBLd9EhlqN4/mv7/mZ68=)
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
# thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    # real mod : true setting
    cache: false
    template-resolver-order: 0
# jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: DefaultPassword

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8080
---

spring:
  profiles: docker
  cloud:

