logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace
  file:
    path: target/logs

server:
  port: 8080

spring:
  profiles:
    active: local
    include: google
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      validation-timeout: 40000
    sql-script-encoding: UTF-8
    initialization-mode: embedded
  jpa:
    show-sql: true
    use_sql_comments: true
    format_sql: true
    query.in_clause_parameter_padding: true
    properties:
      hibernate:
        ddl-auto: create
    open-in-view: false
  jackson:
    default-property-inclusion: non_empty
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
# thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
  # real mod : true setting
    cache: false
    template-resolver-order: 0

#local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testDB;mode=MySQL;DB_CLOSE_DELAY=-1
#    username: ENC(bn7gNC9SEFcbStq4dDtVuw==)
#    password: ENC(px9ud7xYJVB4/MW8CSH7kw==)
    username: test
    password: test
    driver-class-name: org.h2.Driver
    characterEncoding: UTF-8
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  hibernate:
    connection:
      characterEncoding: UTF-8
# jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# my encryption Value setting
#my:
#  test:
#    encValue: ENC(fUVcZWs6qa29DzgpZmRp9BK2blyWSF2V)