apiVersion: apps/v1
kind: Deployment
metadata:
  name: Importexpendituremanagement
  labels:
    app: Importexpendituremanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Importexpendituremanagement
  template:
    metadata:
      labels:
        app: Importexpendituremanagement
    spec:
      containers:
        - name: Importexpendituremanagement
          image: username/Importexpendituremanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5