apiVersion: v1
kind: Service
metadata:
  name: Importexpendituremanagement
  labels:
    app: Importexpendituremanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Importexpendituremanagement