apiVersion: v1
kind: Service
metadata:
  name: Incomexpendituremanagement
  labels:
    app: Incomexpendituremanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Incomexpendituremanagement