
server:
  port: 8080
---

spring:
  profiles: default
  # JPA 설정
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
    show_sql: true
    format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

  # SpringData REST의 기본 context path
  data.rest.basePath: api

  # H2 DB설정
#  datasource:
#    url: jdbc:h2:file:./db/devdb;AUTO_SERVER=TRUE
#    username: test
#    password: test
#    driver-class-name: org.h2.Driver
  # MySQL DB설정
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
#  h2:
#    console.enabled: true
#    console.path: /console

#  data:
#    mongodb:
#      authentication-database: admin
#      username: jjangee
#      password: test
#      database: testdb
#      port: 27017
#      host: localhost

  cloud:

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8081
---

spring:
  profiles: docker
  cloud:

