
server:
  port: 8080
---

spring:
  profiles: default
  # JPA 설정
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
  # SpringData REST의 기본 context path
  data.rest.basePath: api

  # H2 DB설정
  datasource:
    url: jdbc:h2:file:./db/devdb;AUTO_SERVER=TRUE
    username: test
    password: test
    driver-class-name: org.h2.Driver

  h2:
    console.enabled: true
    console.path: /console

  cloud:

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8081
---

spring:
  profiles: docker
  cloud:

