
server:
  port: 8080
---

spring:
  profiles: default
# JPA 설정
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
    show_sql: true
    format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

#   SpringData REST의 기본 context path
  data.rest.basePath: api

#   H2 DB설정
#  datasource:
#    url: jdbc:h2:file:./db/devdb;AUTO_SERVER=TRUE
#    username: test
#    password: test
#    driver-class-name: org.h2.Driver
#    h2:
#      console.enabled: true
#      console.path: /console

#   MySQL DB설정
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/home?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    #    username: test
    #    password: test
    username: ENC(Idv0U0KIbsslp/99l3hBN887zHbbzuPCPdrDurPkt2M=)
    password: ENC(ivMd8IXHu+N4K9zVNB3+9F2tBLd9EhlqN4/mv7/mZ68=)
    driver-class-name: com.mysql.jdbc.Driver


#  data:
#    mongodb:
#      authentication-database: admin
#      username: jjangee
#      password: test
#      database: testdb
#      port: 27017
#      host: localhost

  cloud:

# jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: "DefaultPassword"
my:
  seedkey:
    key1: ENC(lZVqIfmTZbLDi3qO3fekx8XY9mEUS3zaM5vfxViG6TBg2ZAofGfELA7y0Uhhp9rH)
    key2: ENC(Rw4e0fCoAyvNK7SSBWolCxInzYSCwFNGv2+x/ku0Wi3uyWZDqqzGr8OtTPy+4hfP)

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8081
---

spring:
  profiles: docker
  cloud:

